Hw02 fix app
kvs4/home_work_basic pull request #3
Opened 2024-04-25 15:49 UTC by kvs4

## Домашнее задание №2 «Чиним, собираем и запускаем приложение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Приложение локально собирается
- [ ] Линтер не выдает ошибок при локальном запуске

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла

#### Зачёт от 4 баллов

2024-04-26 15:35 UTC, vladislavmass requested changes

2024-04-26 15:35 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
>  		fmt.Printf("Error: %v", err)
Ошибка надо возвращать, а не просто выводить `return nil,err`

2024-04-26 15:35 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
>  		return nil, nil
Ошибка надо возвращать, а не просто выводить `return nil,err`

2024-04-26 15:35 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
> +		return nil, nil
Ошибка надо возвращать, а не просто выводить `return nil,err`

2024-04-26 15:35 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
>  	res := data
Эта строчка лишняя, можно сразу вернуть Data

2024-04-26 15:35 UTC, vladislavmass commented on hw02_fix_app/go.mod
>  module github.com/fixme_my_friend/hw02_fix_app
Нервное имя модуля

2024-04-27 14:13 UTC, kvs4 commented on hw02_fix_app/reader/pkg.go
>  		fmt.Printf("Error: %v", err)
Поправил

2024-04-27 14:13 UTC, kvs4 commented on hw02_fix_app/reader/pkg.go
>  		return nil, nil
Поправил

2024-04-27 14:13 UTC, kvs4 commented on hw02_fix_app/reader/pkg.go
> +		return nil, nil
Поправил

2024-04-27 14:13 UTC, kvs4 commented on hw02_fix_app/reader/pkg.go
>  	res := data
Поправил

2024-04-27 14:13 UTC, kvs4 commented on hw02_fix_app/go.mod
>  module github.com/fixme_my_friend/hw02_fix_app
Поправил

2024-04-27 14:16 UTC, vladislavmass requested changes

2024-04-27 14:16 UTC, vladislavmass commented on hw02_fix_app/go.mod
> +module github.com/kvs4/home_work_basic/tree/hw02_fix_app
Неверное имя модуля .`github.com/kvs4/home_work_basic/hw02_fix_app`

2024-04-27 20:21 UTC, kvs4 commented on hw02_fix_app/go.mod
> +module github.com/kvs4/home_work_basic/tree/hw02_fix_app
Поправил

2024-04-27 20:59 UTC, vladislavmass approved these changes

2024-05-02 20:54 UTC, merged